# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solution: 'HotelSystem_Frontend/HotelSystem_Frontend.sln'


steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.Config'

- task: MSBuild@1
  inputs:
    solution: 'HotelSystem_Frontend/ServiceProxy/*.csproj'
    
#- script: dotnet build --configuration Release --no-restore DummyInMemoryService/DummyInMemoryService.csproj
#  displayName: 'dotnet build'

- script: dotnet build --configuration Release --no-restore HotelSystem_Frontend/HotelSystem_Frontend.csproj
  displayName: 'dotnet build'
